module.exports = {
  ...require('./device-info'),
  ...require('./downloading'),
  ...require('./exam-questions'),
  ...require('./lesson'),
  ...require('./loading'),
  ...require('./net-info-status'),
  ...require('./permissions'),
  ...require('./settings'),
  ...require('./shelf'),
  ...require('./user-info'),
  ...require('./version'),
  ...require('./words'),
  ...require('./rating-test'),
  ...require('./content-loading'),
  ...require('./banner'),
  ...require('./goods'),
};
